-- Seed: core PIC rows (legal_structure -> process_model -> decision_element)
--
-- Safe to re-run: uses UPSERT by primary key (id).
-- Requires schema from resources/01_supabase_schema.sql to be applied first.

BEGIN;


-- ===== legal_structure =====

INSERT INTO "public"."legal_structure" ("id", "created_at", "title", "citation", "description", "context", "issuing_authority", "effective_date", "compliance_data", "url", "other", "data_record_version", "data_source_agency", "data_source_system", "last_updated", "record_owner_agency", "retrieved_timestamp")
VALUES (1, '2025-10-12 17:16:55.43967+00'::timestamptz, 'CEQ NEPA Guidance: Implementation of the National Environmental Policy Act', NULL, 'The purpose of this memorandum is to provide guidance1 to Federal agencies as to their
implementation of the National Environmental Policy Act (NEPA or the Act).
2 This
memorandum includes an overview of NEPA, including a discussion of recent amendments to
the statute and recent case law as relevant to agency implementation of NEPA. This
memorandum also provides guidance for agencies to use when establishing or revising agencyspecific NEPA implementing procedures. As part of this guidance, CEQ has provided a template
that agencies are encouraged to follow for such NEPA implementing procedures, attached as
Appendix 1.', NULL, 'CEQ', '2025-09-29'::date, NULL, NULL, NULL, 'https://ceq.doe.gov/docs/ceq-regulations-and-guidance/Agency-NEPA-Implementation-Guidance.pdf', 'CEQ', 'nepa.gov', '2025-10-12 17:16:42+00'::timestamptz, 'CEQ', '2025-10-12 17:16:47+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "title" = EXCLUDED."title", "citation" = EXCLUDED."citation", "description" = EXCLUDED."description", "context" = EXCLUDED."context", "issuing_authority" = EXCLUDED."issuing_authority", "effective_date" = EXCLUDED."effective_date", "compliance_data" = EXCLUDED."compliance_data", "url" = EXCLUDED."url", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

-- Keep identity sequences in sync with seeded IDs
SELECT setval('public.legal_structure_id_seq', (SELECT COALESCE(MAX(id), 1) FROM "public"."legal_structure"), true);


-- ===== process_model =====

INSERT INTO "public"."process_model" ("id", "created_at", "title", "description", "notes", "bpmn_model", "legal_structure_id", "legal_structure_text", "screening_description", "screening_desc_json", "agency", "parent_model", "DMN_model", "other", "data_record_version", "data_source_agency", "data_source_system", "last_updated", "record_owner_agency", "retrieved_timestamp")
VALUES (1, '2025-10-06 17:16:54.257077+00'::timestamptz, 'Project Pre-screening', 'Pre-application triage that captures core project data, runs NEPA Assist and IPaC screenings, and organizes permitting and CE logic.', NULL, NULL, 1, NULL, 'Collect inputs for a pre-screening process that initiates a project and starts related permitting and environmental review processes', NULL, 'CEQ Permitting Innovation Center', NULL, NULL, NULL, '1', NULL, NULL, '2025-10-06 17:16:54.257077+00'::timestamptz, 'CEQ', '2025-10-06 17:16:54.257077+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "notes" = EXCLUDED."notes", "bpmn_model" = EXCLUDED."bpmn_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "legal_structure_text" = EXCLUDED."legal_structure_text", "screening_description" = EXCLUDED."screening_description", "screening_desc_json" = EXCLUDED."screening_desc_json", "agency" = EXCLUDED."agency", "parent_model" = EXCLUDED."parent_model", "DMN_model" = EXCLUDED."DMN_model", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

-- Keep identity sequences in sync with seeded IDs
SELECT setval('public.process_model_id_seq', (SELECT COALESCE(MAX(id), 1) FROM "public"."process_model"), true);


-- ===== decision_element =====

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (1, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Complete project information', 'Capture the full project entity as a JSON object to support downstream checks.', 'complete', 1.0, NULL, NULL, NULL, 'Provide complete project details', NULL, NULL, 'complete information', NULL, 'input', NULL, NULL, NULL, '1', NULL, NULL, '{"project":{}}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (2, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Geospatial screening results - NEPA Assist', 'Store raw and summarized NEPA Assist results for the project footprint.', 'complete', 1.0, NULL, true, NULL, 'Confirm or upload NEPA Assist results if auto fetch fails', NULL, NULL, 'complete information', NULL, 'screening', NULL, NULL, NULL, '1', NULL, NULL, '{"nepa_assist_raw":{},"nepa_assist_summary":{}}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (3, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Geospatial screening results - IPAC', 'Store raw and summarized IPaC results for listed species and critical habitat proximity.', 'complete', 1.0, NULL, true, NULL, 'Confirm or upload IPaC results if auto fetch fails', NULL, NULL, 'complete information', NULL, 'screening', NULL, NULL, NULL, '1', NULL, NULL, '{"ipac_raw":{},"ipac_summary":{}}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (4, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Permitting checklist', 'Track candidate permits and approvals as a structured checklist with optional narrative.', 'complete', 1.0, NULL, NULL, NULL, 'Provide permit applicability notes', NULL, NULL, 'complete information', NULL, 'checklist', NULL, NULL, NULL, '1', NULL, NULL, '{"notes":"","permits":[]}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (5, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Categorical exclusion', 'Capture candidate CE citations and rationale.', 'complete', 1.0, NULL, NULL, NULL, 'Enter CE references and rationale', NULL, NULL, 'complete information', NULL, 'ce', NULL, NULL, NULL, '1', NULL, NULL, '{"rationale":"","ce_candidates":[]}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (6, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Conditions', 'Capture mitigation or standard conditions expected to apply.', 'complete', 1.0, NULL, NULL, NULL, 'List applicable conditions and notes', NULL, NULL, 'complete information', NULL, 'conditions', NULL, NULL, NULL, '1', NULL, NULL, '{"notes":"","conditions":[]}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

INSERT INTO "public"."decision_element" ("id", "created_at", "process_model", "legal_structure_id", "title", "description", "measure", "threshold", "spatial", "intersect", "spatial_reference", "form_text", "form_response_desc", "form_data", "evaluation_method", "evaluation_dmn", "category", "process_model_internal_reference_id", "parent_decision_element_id", "other", "data_record_version", "data_source_agency", "data_source_system", "expected_evaluation_data", "last_updated", "record_owner_agency", "response_data", "retrieved_timestamp")
VALUES (7, '2025-10-06 17:16:54.257077+00'::timestamptz, 1, 1, 'Resource area analysis', 'Structured findings by resource area with narrative.', 'complete', 1.0, NULL, NULL, NULL, 'Provide resource-by-resource notes', NULL, NULL, 'complete information', NULL, 'analysis', NULL, NULL, NULL, '1', NULL, NULL, '{"summary":"","resources":[]}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz, 'CEQ', '{"complete":false}'::jsonb, '2025-10-06 17:24:01.521792+00'::timestamptz)
ON CONFLICT ("id") DO UPDATE SET "created_at" = EXCLUDED."created_at", "process_model" = EXCLUDED."process_model", "legal_structure_id" = EXCLUDED."legal_structure_id", "title" = EXCLUDED."title", "description" = EXCLUDED."description", "measure" = EXCLUDED."measure", "threshold" = EXCLUDED."threshold", "spatial" = EXCLUDED."spatial", "intersect" = EXCLUDED."intersect", "spatial_reference" = EXCLUDED."spatial_reference", "form_text" = EXCLUDED."form_text", "form_response_desc" = EXCLUDED."form_response_desc", "form_data" = EXCLUDED."form_data", "evaluation_method" = EXCLUDED."evaluation_method", "evaluation_dmn" = EXCLUDED."evaluation_dmn", "category" = EXCLUDED."category", "process_model_internal_reference_id" = EXCLUDED."process_model_internal_reference_id", "parent_decision_element_id" = EXCLUDED."parent_decision_element_id", "other" = EXCLUDED."other", "data_record_version" = EXCLUDED."data_record_version", "data_source_agency" = EXCLUDED."data_source_agency", "data_source_system" = EXCLUDED."data_source_system", "expected_evaluation_data" = EXCLUDED."expected_evaluation_data", "last_updated" = EXCLUDED."last_updated", "record_owner_agency" = EXCLUDED."record_owner_agency", "response_data" = EXCLUDED."response_data", "retrieved_timestamp" = EXCLUDED."retrieved_timestamp";

-- Keep identity sequences in sync with seeded IDs
SELECT setval('public.process_decision_element_id_seq', (SELECT COALESCE(MAX(id), 1) FROM "public"."decision_element"), true);


COMMIT;
