// NEPA implementing procedures by federal agency
// Sources: CE Catalog spreadsheet (79 agency tabs) + NEPA Procedures PDF (citations/URLs)

import type { IntegrationStatus } from "./permitInventory"

export type NepaAgency = {
  id: string
  abbreviation: string
  name: string
  department: string
  departmentAbbreviation: string
  procedureCitation: string
  procedureUrl: string
  integrationStatus: IntegrationStatus
}

export const nepaAgencies: NepaAgency[] = [
  // ── Department of Agriculture (USDA) ──
  {
    id: "usda",
    abbreviation: "USDA",
    name: "U.S. Department of Agriculture",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "7 CFR Part 1b",
    procedureUrl: "https://www.ecfr.gov/current/title-7/subtitle-A/part-1b",
    integrationStatus: "manual",
  },
  {
    id: "usda-ars",
    abbreviation: "ARS",
    name: "Agricultural Research Service",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "7 CFR Part 520",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/retrieveECFR?gp=1&SID=849f2fdbdeb878e8b309d93c9e9206ff&ty=HTML&h=L&n=pt7.6.520&r=PART",
    integrationStatus: "manual",
  },
  {
    id: "usda-aphis",
    abbreviation: "APHIS",
    name: "Animal and Plant Health Inspection Service",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "7 CFR Part 372",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=d111bf2e93e1cadf40199e8c61596ea2&mc=true&node=pt7.5.372&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "usda-fsa",
    abbreviation: "FSA",
    name: "Farm Service Agency",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "Federal Register (2016-08-03)",
    procedureUrl: "https://www.federalregister.gov/documents/2016/08/03/2016-18075/environmental-policies-and-procedures-compliance-with-the-national-environmental-policy-act-and",
    integrationStatus: "manual",
  },
  {
    id: "usda-usfs",
    abbreviation: "USFS",
    name: "Forest Service",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "Federal Register (2020-11-19)",
    procedureUrl: "https://www.federalregister.gov/documents/2020/11/19/2020-25465/national-environmental-policy-act-nepa-compliance",
    integrationStatus: "manual",
  },
  {
    id: "usda-nrcs",
    abbreviation: "NRCS",
    name: "Natural Resources Conservation Service",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "NRCS NEPA Procedures",
    procedureUrl: "https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/technical/ecosciences/ec/?cid=nrcsdev11_000340",
    integrationStatus: "manual",
  },
  {
    id: "usda-rd",
    abbreviation: "RD",
    name: "Rural Development",
    department: "Department of Agriculture",
    departmentAbbreviation: "USDA",
    procedureCitation: "7 CFR Part 1970",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=fde679bda3c1be0c97f18ce4bac3e2a2&mc=true&node=pt7.14.1970&rgn=div5",
    integrationStatus: "manual",
  },
  // ── Department of Commerce (DOC) ──
  {
    id: "doc",
    abbreviation: "DOC",
    name: "Department of Commerce",
    department: "Department of Commerce",
    departmentAbbreviation: "DOC",
    procedureCitation: "DAO 216-6",
    procedureUrl: "http://www.osec.doc.gov/opog/dmp/daos/dao216_6.html",
    integrationStatus: "manual",
  },
  {
    id: "doc-eda",
    abbreviation: "EDA",
    name: "Economic Development Administration",
    department: "Department of Commerce",
    departmentAbbreviation: "DOC",
    procedureCitation: "13 CFR Part 302",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=31dd691dc8f0dd589b1df607ecd77b36&mc=true&tpl=/ecfrbrowse/Title13/13cfr302_main_02.tpl",
    integrationStatus: "manual",
  },
  {
    id: "doc-firstnet",
    abbreviation: "FirstNet",
    name: "First Responder Network Authority",
    department: "Department of Commerce",
    departmentAbbreviation: "DOC",
    procedureCitation: "FirstNet NEPA Procedures (2018)",
    procedureUrl: "https://www.firstnet.gov/sites/default/files/FirstNet_Implementing_Procedures_January_2018.pdf",
    integrationStatus: "manual",
  },
  {
    id: "doc-ntia",
    abbreviation: "NTIA",
    name: "National Telecommunications and Information Administration",
    department: "Department of Commerce",
    departmentAbbreviation: "DOC",
    procedureCitation: "DAO 216-6 (DOC dept-wide)",
    procedureUrl: "http://www.osec.doc.gov/opog/dmp/daos/dao216_6.html",
    integrationStatus: "manual",
  },
  {
    id: "doc-noaa",
    abbreviation: "NOAA",
    name: "National Oceanic and Atmospheric Administration",
    department: "Department of Commerce",
    departmentAbbreviation: "DOC",
    procedureCitation: "NOAA NEPA Procedures",
    procedureUrl: "http://www.nepa.noaa.gov/",
    integrationStatus: "manual",
  },
  // ── Department of Defense (DOD) ──
  {
    id: "dod-dla",
    abbreviation: "DLA",
    name: "Defense Logistics Agency",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "DLA Regulation 1000.22",
    procedureUrl: "http://www.dla.mil/Portals/104/Documents/J5StrategicPlansPolicy/PublicIssuances/r1000.22.pdf",
    integrationStatus: "manual",
  },
  {
    id: "dod-dtra",
    abbreviation: "DTRA",
    name: "Defense Threat Reduction Agency",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "DTRA NEPA Procedures Guide",
    procedureUrl: "https://www.dtra.mil/Portals/61/Documents/NEPA/DTRASCCWMD_NEPAProceduresGuide.pdf",
    integrationStatus: "manual",
  },
  {
    id: "dod-mda",
    abbreviation: "MDA",
    name: "Missile Defense Agency",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "Federal Register (2014-08-08)",
    procedureUrl: "https://www.govinfo.gov/content/pkg/FR-2014-08-08/pdf/2014-18730.pdf",
    integrationStatus: "manual",
  },
  {
    id: "dod-usaf",
    abbreviation: "USAF",
    name: "United States Air Force",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "32 CFR Part 989",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=cec76a30311d778de544f0fc63b53e89&mc=true&node=pt32.6.989&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "dod-da",
    abbreviation: "DA",
    name: "Department of the Army",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "32 CFR Part 651",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=23fc57625bc5e7981c8af33263139b75&mc=true&node=pt32.4.651&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "dod-don",
    abbreviation: "DON",
    name: "Department of the Navy",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "32 CFR Part 775",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=23fc57625bc5e7981c8af33263139b75&mc=true&node=pt32.5.775&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "dod-usace",
    abbreviation: "USACE",
    name: "U.S. Army Corps of Engineers",
    department: "Department of Defense",
    departmentAbbreviation: "DOD",
    procedureCitation: "33 CFR Part 230",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=78a7fc47dd583aa0637153c238efba43&mc=true&tpl=/ecfrbrowse/Title33/33cfr230_main_02.tpl",
    integrationStatus: "manual",
  },
  // ── Department of Energy (DOE) ──
  {
    id: "doe",
    abbreviation: "DOE",
    name: "Department of Energy",
    department: "Department of Energy",
    departmentAbbreviation: "DOE",
    procedureCitation: "10 CFR Part 1021",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=a4e055019b59e975ce6b588a419d7b2d&mc=true&node=pt10.4.1021&rgn=div5",
    integrationStatus: "manual",
  },
  // ── Department of Health and Human Services (HHS) ──
  {
    id: "hhs",
    abbreviation: "HHS",
    name: "Department of Health and Human Services",
    department: "Department of Health and Human Services",
    departmentAbbreviation: "HHS",
    procedureCitation: "HHS General Administration Manual Part 30",
    procedureUrl: "https://web.archive.org/web/20170430115722/https:/www.hhs.gov/hhs-manuals/gam-part-30/index.html",
    integrationStatus: "manual",
  },
  {
    id: "hhs-fda",
    abbreviation: "FDA",
    name: "Food and Drug Administration",
    department: "Department of Health and Human Services",
    departmentAbbreviation: "HHS",
    procedureCitation: "21 CFR Part 25",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/retrieveECFR?gp&SID=ddad1cfe588afe86cbfd9c60eac256bf&mc=true&n=pt21.1.25&r=PART&ty=HTML",
    integrationStatus: "manual",
  },
  {
    id: "hhs-ihs",
    abbreviation: "IHS",
    name: "Indian Health Service",
    department: "Department of Health and Human Services",
    departmentAbbreviation: "HHS",
    procedureCitation: "IHS NEPA Handbook",
    procedureUrl: "https://www.ihs.gov/sites/oehe/themes/responsive2017/display_objects/documents/handbook/02301.pdf",
    integrationStatus: "manual",
  },
  {
    id: "hhs-nih",
    abbreviation: "NIH",
    name: "National Institutes of Health",
    department: "Department of Health and Human Services",
    departmentAbbreviation: "HHS",
    procedureCitation: "Federal Register (2000)",
    procedureUrl: "https://www.federalregister.gov/d/00-1128",
    integrationStatus: "manual",
  },
  // ── Department of Homeland Security (DHS) ──
  {
    id: "dhs",
    abbreviation: "DHS",
    name: "Department of Homeland Security",
    department: "Department of Homeland Security",
    departmentAbbreviation: "DHS",
    procedureCitation: "DHS NEPA Implementing Procedures",
    procedureUrl: "https://www.dhs.gov/national-environmental-policy-act-nepa-department-homeland-security-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "dhs-tsa",
    abbreviation: "TSA",
    name: "Transportation Security Administration",
    department: "Department of Homeland Security",
    departmentAbbreviation: "DHS",
    procedureCitation: "DHS NEPA Implementing Procedures",
    procedureUrl: "https://www.dhs.gov/national-environmental-policy-act-nepa-department-homeland-security-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "dhs-fletc",
    abbreviation: "FLETC",
    name: "Federal Law Enforcement Training Center",
    department: "Department of Homeland Security",
    departmentAbbreviation: "DHS",
    procedureCitation: "DHS NEPA Implementing Procedures",
    procedureUrl: "https://www.dhs.gov/national-environmental-policy-act-nepa-department-homeland-security-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "dhs-cbp",
    abbreviation: "CBP",
    name: "Customs and Border Protection",
    department: "Department of Homeland Security",
    departmentAbbreviation: "DHS",
    procedureCitation: "DHS NEPA Implementing Procedures",
    procedureUrl: "https://www.dhs.gov/national-environmental-policy-act-nepa-department-homeland-security-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "dhs-uscg",
    abbreviation: "USCG",
    name: "U.S. Coast Guard",
    department: "Department of Homeland Security",
    departmentAbbreviation: "DHS",
    procedureCitation: "DHS NEPA Implementing Procedures",
    procedureUrl: "https://www.dhs.gov/national-environmental-policy-act-nepa-department-homeland-security-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "dhs-fema",
    abbreviation: "FEMA",
    name: "Federal Emergency Management Agency",
    department: "Department of Homeland Security",
    departmentAbbreviation: "DHS",
    procedureCitation: "DHS NEPA Implementing Procedures",
    procedureUrl: "https://www.dhs.gov/national-environmental-policy-act-nepa-department-homeland-security-implementing-procedures",
    integrationStatus: "manual",
  },
  // ── Department of Housing and Urban Development (HUD) ──
  {
    id: "hud",
    abbreviation: "HUD",
    name: "Department of Housing and Urban Development",
    department: "Department of Housing and Urban Development",
    departmentAbbreviation: "HUD",
    procedureCitation: "Federal Register (2003-09-29) / 24 CFR Part 58",
    procedureUrl: "https://www.federalregister.gov/documents/2003/09/29/03-24265/environmental-review-procedures-for-entities-assuming-huds-environmental-responsibilities",
    integrationStatus: "manual",
  },
  // ── Department of the Interior (DOI) ──
  {
    id: "doi",
    abbreviation: "DOI",
    name: "Department of the Interior",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "43 CFR Part 46",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?c=ecfr&sid=5b7d48406ac85aeb9c4ce853f50c18ce&tpl=/ecfrbrowse/Title43/43cfr46_main_02.tpl",
    integrationStatus: "manual",
  },
  {
    id: "doi-usfws",
    abbreviation: "USFWS",
    name: "U.S. Fish and Wildlife Service",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 8",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/chapter_8_managing_the_nepa_process-u.s._fish_and_wildlife_service.doc",
    integrationStatus: "manual",
  },
  {
    id: "doi-usgs",
    abbreviation: "USGS",
    name: "U.S. Geological Survey",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 9",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/516-dm-9.pdf",
    integrationStatus: "manual",
  },
  {
    id: "doi-bia",
    abbreviation: "BIA",
    name: "Bureau of Indian Affairs",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 10",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/chapte1_10.doc",
    integrationStatus: "manual",
  },
  {
    id: "doi-blm",
    abbreviation: "BLM",
    name: "Bureau of Land Management",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 14",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/chapte1_14.doc",
    integrationStatus: "manual",
  },
  {
    id: "doi-nps",
    abbreviation: "NPS",
    name: "National Park Service",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 12",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/516-dm-12.pdf",
    integrationStatus: "manual",
  },
  {
    id: "doi-osm",
    abbreviation: "OSM",
    name: "Office of Surface Mining",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "Directive 995 NEPA Handbook",
    procedureUrl: "https://www.osmre.gov/sites/default/files/pdfs/directive995_NEPAHandbook.pdf",
    integrationStatus: "manual",
  },
  {
    id: "doi-bor",
    abbreviation: "BOR",
    name: "Bureau of Reclamation",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 20",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/chapte1_20.doc",
    integrationStatus: "manual",
  },
  {
    id: "doi-boem",
    abbreviation: "BOEM",
    name: "Bureau of Ocean Energy Management / BSEE",
    department: "Department of the Interior",
    departmentAbbreviation: "DOI",
    procedureCitation: "516 DM Chapter 15",
    procedureUrl: "https://www.doi.gov/sites/doi.gov/files/elips/documents/516-dm-15.pdf",
    integrationStatus: "manual",
  },
  // ── Department of Justice (DOJ) ──
  {
    id: "doj-bop",
    abbreviation: "BOP",
    name: "Bureau of Prisons",
    department: "Department of Justice",
    departmentAbbreviation: "DOJ",
    procedureCitation: "28 CFR Part 61, Appendix A",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt28.2.61&rgn=div5&ap28.2.61.0000_0nbspnbspnbsp.a",
    integrationStatus: "manual",
  },
  {
    id: "doj-dea",
    abbreviation: "DEA",
    name: "Drug Enforcement Administration",
    department: "Department of Justice",
    departmentAbbreviation: "DOJ",
    procedureCitation: "28 CFR Part 61, Appendix B",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt28.2.61&rgn=div5&ap28.2.61.0000_0nbspnbspnbsp.b",
    integrationStatus: "manual",
  },
  {
    id: "doj-ins",
    abbreviation: "INS",
    name: "Immigration and Naturalization Service",
    department: "Department of Justice",
    departmentAbbreviation: "DOJ",
    procedureCitation: "28 CFR Part 61",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt28.2.61&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "doj-ojars",
    abbreviation: "OJARS",
    name: "Office of Justice Assistance, Research, and Statistics",
    department: "Department of Justice",
    departmentAbbreviation: "DOJ",
    procedureCitation: "28 CFR Part 61, Appendix D",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt28.2.61&rgn=div5&ap28.2.61.0000_0nbspnbspnbsp.d",
    integrationStatus: "manual",
  },
  {
    id: "doj-usms",
    abbreviation: "USMS",
    name: "United States Marshals Service",
    department: "Department of Justice",
    departmentAbbreviation: "DOJ",
    procedureCitation: "28 CFR Part 61, Appendix E",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt28.2.61&rgn=div5&ap28.2.61.0000_0nbspnbspnbsp.e",
    integrationStatus: "manual",
  },
  {
    id: "doj-fbi",
    abbreviation: "FBI",
    name: "Federal Bureau of Investigation",
    department: "Department of Justice",
    departmentAbbreviation: "DOJ",
    procedureCitation: "28 CFR Part 61, Appendix F",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt28.2.61&rgn=div5&ap28.2.61.0000_0nbspnbspnbsp.f",
    integrationStatus: "manual",
  },
  // ── Department of Labor (DOL) ──
  {
    id: "dol",
    abbreviation: "DOL",
    name: "Department of Labor",
    department: "Department of Labor",
    departmentAbbreviation: "DOL",
    procedureCitation: "29 CFR Part 11",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=f9fda319ad830e1df360477a298f6997&node=pt29.1.11&rgn=div5",
    integrationStatus: "manual",
  },
  // ── Department of State (DOS) ──
  {
    id: "dos",
    abbreviation: "DOS",
    name: "Department of State",
    department: "Department of State",
    departmentAbbreviation: "DOS",
    procedureCitation: "22 CFR Part 161",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=b3d2565d536010f83f1e6eab438bd0f7&node=pt22.1.161&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "dos-ibwc",
    abbreviation: "IBWC",
    name: "International Boundary and Water Commission",
    department: "Department of State",
    departmentAbbreviation: "DOS",
    procedureCitation: "Federal Register (1981)",
    procedureUrl: "https://ceq.doe.gov/docs/laws-regulations/USIBWC-NEPA-procedures-46FR044083-1981.pdf",
    integrationStatus: "manual",
  },
  // ── Department of Transportation (DOT) ──
  {
    id: "dot",
    abbreviation: "DOT",
    name: "Department of Transportation",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "DOT Order 5610.1C",
    procedureUrl: "https://www.transportation.gov/sites/dot.gov/files/docs/Procedures_Considering_Environmental_Impacts_5610_1C.pdf",
    integrationStatus: "manual",
  },
  {
    id: "dot-faa",
    abbreviation: "FAA",
    name: "Federal Aviation Administration",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "FAA Order 1050.1F",
    procedureUrl: "https://www.faa.gov/documentlibrary/media/order/faa_order_1050_1f.pdf",
    integrationStatus: "manual",
  },
  {
    id: "dot-fhwa",
    abbreviation: "FHWA",
    name: "Federal Highway Administration",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "23 CFR Part 771",
    procedureUrl: "https://www.ecfr.gov/current/title-23/chapter-I/subchapter-H/part-771",
    integrationStatus: "manual",
  },
  {
    id: "dot-fmcsa",
    abbreviation: "FMCSA",
    name: "Federal Motor Carrier Safety Administration",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "Federal Register (2004-03-01)",
    procedureUrl: "https://www.federalregister.gov/documents/2004/03/01/04-4338/national-environmental-policy-act-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "dot-fra",
    abbreviation: "FRA",
    name: "Federal Railroad Administration",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "23 CFR Part 771",
    procedureUrl: "https://www.ecfr.gov/current/title-23/part-771",
    integrationStatus: "manual",
  },
  {
    id: "dot-fta",
    abbreviation: "FTA",
    name: "Federal Transit Administration",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "23 CFR Part 771",
    procedureUrl: "https://www.ecfr.gov/current/title-23/part-771",
    integrationStatus: "manual",
  },
  {
    id: "dot-marad",
    abbreviation: "MARAD",
    name: "Maritime Administration",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "MAO 600-001",
    procedureUrl: "https://www.maritime.dot.gov/sites/marad.dot.gov/files/docs/environment-security-safety/office-environment/596/mao600-001-0.pdf",
    integrationStatus: "manual",
  },
  {
    id: "dot-slsdc",
    abbreviation: "SLSDC",
    name: "Saint Lawrence Seaway Development Corporation",
    department: "Department of Transportation",
    departmentAbbreviation: "DOT",
    procedureCitation: "SLSDC NEPA Regulations",
    procedureUrl: "https://www.seaway.dot.gov/sites/seaway.dot.gov/files/docs/SLSDC%20NEPA%20Regulations.pdf",
    integrationStatus: "manual",
  },
  // ── Department of Treasury ──
  {
    id: "treas",
    abbreviation: "TREAS",
    name: "Department of the Treasury",
    department: "Department of the Treasury",
    departmentAbbreviation: "TREAS",
    procedureCitation: "TD 75-02",
    procedureUrl: "https://www.treasury.gov/about/role-of-treasury/orders-directives/Pages/td75-02.aspx",
    integrationStatus: "manual",
  },
  // ── Department of Veterans Affairs ──
  {
    id: "va",
    abbreviation: "VA",
    name: "Department of Veterans Affairs",
    department: "Department of Veterans Affairs",
    departmentAbbreviation: "VA",
    procedureCitation: "38 CFR Part 26",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&node=pt38.2.26&rgn=div5",
    integrationStatus: "manual",
  },
  // ── Independent Agencies ──
  {
    id: "nasa",
    abbreviation: "NASA",
    name: "National Aeronautics and Space Administration",
    department: "Independent Agency",
    departmentAbbreviation: "NASA",
    procedureCitation: "14 CFR Part 1216.3",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=e91f3312934586fd065729a56876cbea&node=sp14.5.1216.1216_13&rgn=div6",
    integrationStatus: "manual",
  },
  {
    id: "usaid",
    abbreviation: "USAID",
    name: "U.S. Agency for International Development",
    department: "Independent Agency",
    departmentAbbreviation: "USAID",
    procedureCitation: "22 CFR Part 216",
    procedureUrl: "https://www.ecfr.gov/current/title-22/part-216",
    integrationStatus: "manual",
  },
  {
    id: "afrh",
    abbreviation: "AFRH",
    name: "Armed Forces Retirement Home",
    department: "Independent Agency",
    departmentAbbreviation: "AFRH",
    procedureCitation: "38 CFR Part 200",
    procedureUrl: "https://www.ecfr.gov/current/title-38/chapter-II/part-200",
    integrationStatus: "manual",
  },
  {
    id: "cpsc",
    abbreviation: "CPSC",
    name: "Consumer Product Safety Commission",
    department: "Independent Agency",
    departmentAbbreviation: "CPSC",
    procedureCitation: "16 CFR Part 1021",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=9cb1aa80ff3a3962fb6c5a0d57b04a94&node=pt16.2.1021&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "dc",
    abbreviation: "DC",
    name: "Denali Commission",
    department: "Independent Agency",
    departmentAbbreviation: "DC",
    procedureCitation: "45 CFR Part 900",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=0ea7a72a127e308d2223c62017be7054&mc=true&tpl=/ecfrbrowse/Title45/45cfr900_main_02.tpl",
    integrationStatus: "manual",
  },
  {
    id: "epa",
    abbreviation: "EPA",
    name: "Environmental Protection Agency",
    department: "Independent Agency",
    departmentAbbreviation: "EPA",
    procedureCitation: "40 CFR Part 6",
    procedureUrl: "https://www.ecfr.gov/current/title-40/part-6",
    integrationStatus: "manual",
  },
  {
    id: "fcc",
    abbreviation: "FCC",
    name: "Federal Communications Commission",
    department: "Independent Agency",
    departmentAbbreviation: "FCC",
    procedureCitation: "47 CFR Part 1, Subpart I",
    procedureUrl: "https://www.ecfr.gov/current/title-47/part-1/subpart-i",
    integrationStatus: "manual",
  },
  {
    id: "fdic",
    abbreviation: "FDIC",
    name: "Federal Deposit Insurance Corporation",
    department: "Independent Agency",
    departmentAbbreviation: "FDIC",
    procedureCitation: "FDIC NEPA Procedures",
    procedureUrl: "https://www.fdic.gov/regulations/applications/resources/apps-proc-manual/section-01-08-nepa.pdf",
    integrationStatus: "manual",
  },
  {
    id: "ferc",
    abbreviation: "FERC",
    name: "Federal Energy Regulatory Commission",
    department: "Independent Agency",
    departmentAbbreviation: "FERC",
    procedureCitation: "18 CFR Part 380",
    procedureUrl: "https://www.ecfr.gov/current/title-18/chapter-I/subchapter-W/part-380",
    integrationStatus: "manual",
  },
  {
    id: "fmc",
    abbreviation: "FMC",
    name: "Federal Maritime Commission",
    department: "Independent Agency",
    departmentAbbreviation: "FMC",
    procedureCitation: "46 CFR Part 504",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=bc73b40a21180d1ef96eb4afc9607276&node=pt46.9.504&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "gsa",
    abbreviation: "GSA",
    name: "General Services Administration",
    department: "Independent Agency",
    departmentAbbreviation: "GSA",
    procedureCitation: "PBS NEPA Desk Guide",
    procedureUrl: "https://www.gsa.gov/cdnstatic/PBS_NEPA_Deskguide.pdf",
    integrationStatus: "manual",
  },
  {
    id: "restore",
    abbreviation: "RESTORE",
    name: "Gulf Coast Ecosystem Restoration Council",
    department: "Independent Agency",
    departmentAbbreviation: "RESTORE",
    procedureCitation: "RESTORE Council NEPA Procedures",
    procedureUrl: "https://www.restorethegulf.gov/sites/default/files/documents/pdf/Gulf%20Coast%20Ecosystem%20Restoration%20Council%20NEPA%20Procedures.pdf",
    integrationStatus: "manual",
  },
  {
    id: "ncpc",
    abbreviation: "NCPC",
    name: "National Capital Planning Commission",
    department: "Independent Agency",
    departmentAbbreviation: "NCPC",
    procedureCitation: "1 CFR Part 601",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=20e86e514849dc33c11de520730a2fdf&mc=true&tpl=/ecfrbrowse/Title01/1cfr601_main_02.tpl",
    integrationStatus: "manual",
  },
  {
    id: "neh",
    abbreviation: "NEH",
    name: "National Endowment for the Humanities",
    department: "Independent Agency",
    departmentAbbreviation: "NEH",
    procedureCitation: "Federal Register (2019-05-23)",
    procedureUrl: "https://www.federalregister.gov/documents/2019/05/23/2019-10745/national-environmental-policy-act-implementing-procedures",
    integrationStatus: "manual",
  },
  {
    id: "nrc",
    abbreviation: "NRC",
    name: "Nuclear Regulatory Commission",
    department: "Independent Agency",
    departmentAbbreviation: "NRC",
    procedureCitation: "10 CFR Part 51, Subpart A",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=e9eb3057f44ec8da14baeafb8f47ce2a&mc=true&node=sp10.2.51.a&rgn=div6",
    integrationStatus: "manual",
  },
  {
    id: "nsf",
    abbreviation: "NSF",
    name: "National Science Foundation",
    department: "Independent Agency",
    departmentAbbreviation: "NSF",
    procedureCitation: "45 CFR Part 640",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=e91f3312934586fd065729a56876cbea&node=pt45.3.640&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "presidio",
    abbreviation: "PRESIDIO",
    name: "Presidio Trust",
    department: "Independent Agency",
    departmentAbbreviation: "PRESIDIO",
    procedureCitation: "36 CFR Part 1010",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=9bb68c3677c7b9e878fbf7c008eed13d&mc=true&node=pt36.3.1010&rgn=div5",
    integrationStatus: "manual",
  },
  {
    id: "sba",
    abbreviation: "SBA",
    name: "Small Business Administration",
    department: "Independent Agency",
    departmentAbbreviation: "SBA",
    procedureCitation: "SBA NEPA Procedures",
    procedureUrl: "https://www.sba.gov/about-sba/sba-performance/policy-regulations/standard-operating-procedures/national-environmental-policy-act",
    integrationStatus: "manual",
  },
  {
    id: "tva",
    abbreviation: "TVA",
    name: "Tennessee Valley Authority",
    department: "Independent Agency",
    departmentAbbreviation: "TVA",
    procedureCitation: "18 CFR Part 1318",
    procedureUrl: "https://www.ecfr.gov/cgi-bin/text-idx?SID=72f5b57ea48e1ac93f4628e4ff314437&mc=true&tpl=/ecfrbrowse/Title18/18cfr1318_main_02.tpl",
    integrationStatus: "manual",
  },
  {
    id: "usps",
    abbreviation: "USPS",
    name: "U.S. Postal Service",
    department: "Independent Agency",
    departmentAbbreviation: "USPS",
    procedureCitation: "39 CFR Part 775",
    procedureUrl: "http://www.ecfr.gov/cgi-bin/text-idx?SID=72ea18f696b857b68a2bfdf78c4c9052&tpl=/ecfrbrowse/Title39/39cfr775_main_02.tpl",
    integrationStatus: "manual",
  },
]

export function getNepaAgencyUrl(id: string): string {
  return `/nepa-info/${id}`
}
